name: Python Template for IDS706

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 main.py

    # - name: Run tests
    #   run: pytest -v test_main.py

    - name: Test with coverage
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report -m

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: reports/

    - name: Security scan
      uses: pyupio/safety-action@v1
      with:
        args: --full-report



